#[프로젝트 정보 - actuator info에 노출]
info:
  group: "@project.groupId@"
  artifact: "@project.artifactId@"
  name: "@project.name@"
  description: "@project.description@"
  version: "@project.version@"
  contact: 정성현 <hashmap27@gmail.com>
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"

#[Application 설정]
app-config:
  test: "테스트설정값"

#[Server 설정]
server:
  use-forward-headers: true   # X-Forwarded-* 사용을 위함.
  tomcat:
    max-threads: 400 #default 200

#[Spring 설정]
spring:
  application:
    name: "@project.artifactId@"
  aop:
    auto: true  #Add @EnableAspectJAutoProxy
    proxy-target-class: true  #whether subclass-based (CGLIB) proxies are to be create (true)
  #PID 파일 기록 설정
  pid:
    fail-on-write-error: true   #PID파일 기록에 실패할 경우 에러
    file: "@project.artifactId@.pid"    #PID 파일명
  #Spring MVC 설정
  mvc:
    #Content 협상(json/xml)
    contentnegotiation:
      favor-parameter: true
      media-types:
        json: application/json
        xml: application/xml
    #JSP 설정
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  #UTF-8 인코딩 설정
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  #Jackson 기본 설정(최소)
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
    joda-date-time-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
    time-zone: "Asia/Seoul"
    locale: "ko_KR"
    serialization:
      write-dates-as-timestamps: false  #TimeStamp 쓰기 금지.
      #활성화 시 Java8 DateTime.ISO_ZONED_DATE_TIME로 직렬화(ex.'2011-12-03T10:15:30+01:00[Europe/Paris]). ISO-8601사양에서 해당 정보가 포함된 형식 정의하지 않으면 호환성 문제 발생 가능. 비활성 처리.
      write-dates-with-zone-id: false
      indent-output: false  #들여쓰기 여부
    deserialization:
      fail-on-unknown-properties: false #알지못하는 properties가 들어올 경우 실패처리 할지 여부
    mapper:
      sort-properties-alphabetically: false #직렬화시 알파벳 정렬 여부. 비활성화 처리.
  #Devtools 설정
  devtools:
    restart:
      enabled: true   #소스 수정 시 자동 재시작 설정
  #출력 설정
  output:
    ansi:
      enabled: never  #ANSI-colored 출력 사용 하지 않음

#[Actuator 설정]
management:
  endpoints:
    jmx:
      exposure:
        include: info, health
    web:
      base-path: /management
      exposure:
        include: info, health
  info:
    defaults:
      enabled: true

#[MyBatis 설정]
mybatis:
  configuration:
    default-statement-timeout: 300  #기본타입아웃값(초)
    map-underscore-to-camel-case: true  #UnderScore표기법에서 CamelCase표기법으로 변경 가능여부. default: false
    jdbc-type-for-null: nvarchar  #null인 경우 JDBC DataType을 어떤 것으로 처리할지
    log-prefix: "[SQL]" #Logging 접두어
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl   #Logging 구현체 - Mybatis JAR내 logging 구현체 클래스를 찾으면 됨.
    safe-result-handler-enabled: false  #중첩된 문장에서 ResultHandler 사용가능 여부.
    default-fetch-size: 1000  #기본 패칭 크기
  type-handlers-package: #추가 타입 핸들러 패키지 목록 정의
  mapper-locations:
  - "mybatis/common/mybatis-mapper-mysql.xml" #MySql 공통
  #- "mybatis/common/mybatis-mapper-oracle.xml"  #Oracle 공통
  - "mybatis/mapper/**/*.xml"
#[Logback설정 - 전체 커스텀 설정]
logging:
  config: classpath:logback-spring.xml