#[프로젝트 정보 - actuator info에 노출]
info:
  group: "@project.groupId@"
  artifact: "@project.artifactId@"
  name: "@project.name@"
  description: "@project.description@"
  version: "@project.version@"
  contact: 민병돈, 이장완, 정성현
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      source: "@java.version@"
      target: "@java.version@"

#[Application 설정]
app-config:
  test: "테스트설정값"

#[Spring 설정]
spring:
  application:
    name: "@project.artifactId@"
  #Spring MVC 설정
  mvc:
    #Content 협상(json/xml)
    contentnegotiation:
      favor-parameter: true
      media-types:
        json: application/json
        xml: application/xml
    #JSP 설정
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  #UTF-8 인코딩 설정
  http:
    encoding:
      enabled: true
      force: true
      charset: utf-8  